use_frameworks!

platform :ios, '8.0'

target 'LNImageCicleScrollView_Example' do
  pod 'LNImageCicleScrollView', :path => '../'

  target 'LNImageCicleScrollView_Tests' do
    inherit! :search_paths

    
  end
end
